"""
Transcript finalization and index generation.

Appends monthly stats footers and generates README.md index.
"""

import calendar
import re
from pathlib import Path


_LOGS_DIR = Path(__file__).parent.parent.parent / "data" / "pbp_logs"


def _days_in_month(month_str: str) -> int:
    """Return number of days in a YYYY-MM month."""
    year, month = int(month_str[:4]), int(month_str[5:7])
    return calendar.monthrange(year, month)[1]


def _sanitize_dirname(name: str) -> str:
    """Convert a campaign name to a safe directory name."""
    return "".join(c if c.isalnum() or c in (" ", "-", "_") else "" for c in name).strip().replace(" ", "_")


def finalize_previous_month(campaign_dir: Path, current_month: str,
                            campaign_name: str) -> None:
    """Append a stats footer to the previous month's transcript.

    Only runs once per month transition (idempotent -- checks for existing footer).
    """
    year, month = int(current_month[:4]), int(current_month[5:7])
    if month == 1:
        prev_month_str = f"{year - 1}-12"
    else:
        prev_month_str = f"{year}-{month - 1:02d}"

    prev_file = campaign_dir / f"{prev_month_str}.md"
    if not prev_file.exists():
        return

    try:
        content = prev_file.read_text(encoding="utf-8")
        if "## 📊 Month Summary" in content:
            return
    except Exception:
        return

    stats = _count_month_stats(content)
    if stats["total"] == 0:
        return

    footer = _build_month_footer(stats, prev_month_str)
    with open(prev_file, "a", encoding="utf-8") as f:
        f.write(footer)


def _count_month_stats(content: str) -> dict:
    """Count message stats from a month's transcript content."""
    total = 0
    gm_count = 0
    player_count = 0
    unique_posters: set[str] = set()
    active_dates: set[str] = set()
    poster_counts: dict[str, int] = {}
    word_count = 0

    for line in content.split("\n"):
        if not line.startswith("**"):
            continue
        total += 1

        name_match = re.match(
            r"\*\*(.+?)\*\*(?:\s*\(.*?\))?\s*(?:\[GM\])?\s*\((\d{4}-\d{2}-\d{2})", line
        )
        if name_match:
            poster_name = name_match.group(1)
            date_str = name_match.group(2)
            active_dates.add(date_str)
            unique_posters.add(poster_name)
            poster_counts[poster_name] = poster_counts.get(poster_name, 0) + 1

            if "[GM]" in line:
                gm_count += 1
            else:
                player_count += 1

    # Word count from non-header, non-structural lines
    in_entry = False
    for line in content.split("\n"):
        if line.startswith("**"):
            in_entry = True
            colon_pos = line.rfind("):")
            if colon_pos != -1:
                text_after = line[colon_pos + 2:].strip()
                word_count += len(text_after.split()) if text_after else 0
            continue
        if line.startswith("#") or line.startswith("*PBP transcript") or line.startswith("---"):
            in_entry = False
            continue
        if in_entry and line.strip():
            word_count += len(line.split())

    sorted_posters = sorted(poster_counts.items(), key=lambda x: x[1], reverse=True)

    return {
        "total": total, "gm": gm_count, "player": player_count,
        "unique_posters": len(unique_posters), "active_dates": len(active_dates),
        "word_count": word_count, "sorted_posters": sorted_posters,
    }


def _build_month_footer(stats: dict, month_str: str) -> str:
    """Build the month summary footer text."""
    lines = [
        "",
        "---",
        "",
        "## 📊 Month Summary",
        "",
        f"- **Total messages:** {stats['total']} ({stats['gm']} GM, {stats['player']} player)",
        f"- **Unique posters:** {stats['unique_posters']}",
        f"- **Active days:** {stats['active_dates']}/{_days_in_month(month_str)}",
        f"- **Words written:** ~{stats['word_count']:,}",
        "",
        "**Most active:**",
    ]
    for name, count in stats["sorted_posters"][:5]:
        lines.append(f"- {name}: {count} messages")
    lines.append("")
    return "\n".join(lines)


def update_transcript_index(config: dict) -> None:
    """Generate data/pbp_logs/README.md listing all campaigns and their log files."""
    if not _LOGS_DIR.exists():
        return

    lines = [
        "# PBP Transcripts",
        "",
        "Persistent archive of all play-by-post messages.",
        "Auto-generated by PathWarsNudge bot every hour.",
        "",
        "---",
        "",
    ]

    name_map = {}
    for pair in config.get("topic_pairs", []):
        dir_name = _sanitize_dirname(pair["name"])
        name_map[dir_name] = pair["name"]

    campaign_dirs = sorted(d for d in _LOGS_DIR.iterdir() if d.is_dir())

    for campaign_dir in campaign_dirs:
        display_name = name_map.get(campaign_dir.name, campaign_dir.name)
        log_files = sorted(campaign_dir.glob("*.md"), reverse=True)

        if not log_files:
            continue

        total_entries = 0
        for lf in log_files:
            total_entries += sum(1 for line in open(lf) if line.startswith("**"))

        lines.append(f"## {display_name}")
        lines.append(f"")
        lines.append(f"*{total_entries} messages across {len(log_files)} months*")
        lines.append(f"")

        for lf in log_files:
            entries = sum(1 for line in open(lf) if line.startswith("**"))
            lines.append(f"- [{lf.stem}]({campaign_dir.name}/{lf.name}) ({entries} messages)")

        lines.append("")

    index_path = _LOGS_DIR / "README.md"
    index_path.write_text("\n".join(lines), encoding="utf-8")
