"""Help text for the PBP bot."""

_HELP_TEXT = (
    "PBP Reminder Bot\n"
    "\n"
    "I track activity across PBP campaigns and post automated summaries.\n"
    "\n"
    "What I do:\n"
    "- Alert when a campaign goes quiet (configurable hours)\n"
    "- Warn inactive players at 1, 2, 3 weeks; auto-remove at 4\n"
    "- Post party rosters every few days\n"
    "- Award Player of the Week (most consistent poster)\n"
    "- Post weekly pace reports comparing this week vs last\n"
    "- Cross-campaign leaderboard\n"
    "- Ping players who haven't acted during combat\n"
    "- Recruitment notices when a party is under capacity\n"
    "- Campaign anniversary celebrations\n"
    "- Daily tips about bot features (posted randomly across campaigns)\n"
    "\n"
    "GM commands:\n"
    "/combat [enemies] - Start combat (e.g. /combat Ogre, 2 Skeletons)\n"
    "/round <N> <players|enemies> - Set specific round and phase\n"
    "/next - Advance to next phase (players→enemies→next round)\n"
    "/endcombat - End combat (shows log summary)\n"
    "/enemies [list] - View or set enemy roster\n"
    "/clog <event> - Add combat log entry\n"
    "/pause [reason] - Pause inactivity tracking (planned breaks)\n"
    "/resume - Resume inactivity tracking\n"
    "/kick @player - Remove a player from tracking\n"
    "/setpermanent @player - Mark player as permanent (never auto-removed)\n"
    "/unsetpermanent @player - Remove permanent status from a player\n"
    "/setproxy @absent @poster - Someone else rolls for this character\n"
    "/clearproxy @absent - Measure them on their own posting again\n"
    "/addplayer @user Name - Add a player to roster before they post\n"
    "/scene <name> - Mark a scene boundary in the transcript\n"
    "/note <text> - Add a persistent GM note to this campaign\n"
    "/delnote <N> - Delete a GM note by number\n"
    "/quest <text> - Add an active quest/objective\n"
    "/done <N> - Mark quest N as completed\n"
    "/delquest <N> - Delete quest N\n"
    "/pin <text> - Bookmark a story moment or key info\n"
    "/delpin <N> - Delete a pin\n"
    "/loot <text> - Add item to party loot tracker\n"
    "/delloot <N> - Remove item from loot\n"
    "/npc <name> — <desc> - Add an NPC to the tracker\n"
    "/delnpc <N> - Remove an NPC\n"
    "/condition <target> — <effect> [| duration] - Track a condition\n"
    "/endcondition <N> - Remove a condition\n"
    "/clearconditions - Clear all conditions\n"
    "/hp set <n> <cur>/<max> - Track enemy HP\n"
    "/hp d <n> <amount> - Deal damage\n"
    "/hp h <n> <amount> - Heal\n"
    "/hp remove <n> - Remove an entry\n"
    "/hp clear - Clear all HP entries\n"
    "/clock <n> <segments> - Create a progress clock\n"
    "/tick <n> [N] - Advance a clock\n"
    "/untick <n> [N] - Reverse a clock\n"
    "/delclock <n> - Delete a clock\n"
    "/vote <q> | <opt1> | <opt2> [| ...] - Start a vote\n"
    "/endvote - Close voting and show results\n"
    "/timer <duration> [reason] - Set a response deadline\n"
    "/canceltimer - Cancel the active timer\n"
    "/gm - GM dashboard: all campaigns at a glance\n"
    "\n"
    "Everyone:\n"
    "/help - Show this message\n"
    "/status - Campaign health snapshot\n"
    "/overview - All campaigns at a glance\n"
    "/campaign - Full scoreboard with roster and stats\n"
    "/mystats - Your personal stats (also: /me)\n"
    "/myhistory - 8-week posting sparkline\n"
    "/whosturn - Who has acted in combat and who hasn't\n"
    "/combatlog - View combat log entries\n"
    "/catchup - What happened since you last posted\n"
    "/party - In-fiction party composition\n"
    "/notes - View GM notes for this campaign\n"
    "/quests - View active and completed quests\n"
    "/pins - View bookmarked story moments\n"
    "/lootlist - View party loot\n"
    "/npcs - View tracked NPCs\n"
    "/conditions - View active conditions/buffs\n"
    "/hp - View enemy HP tracker\n"
    "/clocks - View progress clocks\n"
    "/dc <level> [difficulty] - PF2e DC lookup\n"
    "/pick <N> - Vote in an active poll\n"
    "/showvote - Show current vote status\n"
    "/showtimer - Show active timer\n"
    "/summary - Full campaign state at a glance\n"
    "/activity - Posting patterns: busiest hours and days\n"
    "/profile @player - Cross-campaign stats for a player\n"
    "/away [duration] [reason] - Declare an absence (skip warnings)\n"
    "/back - Return from absence\n"
    "/recap [N] - Show last N transcript entries (default 10)\n"
    "/roll <dice> [label] - Roll dice (e.g. 1d20+5 Stealth)\n"
    "/heropoint <campaign> - MVP: claim your weekly Hero Point\n"
    "/boons - View your held boons in this campaign\n"
    "/boonsall - View all your boons across all campaigns"
)
